### ISSUE TITLE
文件无效\meta\user\TriggerData.txt

### ISSUE THREAD

**Issue by 1143910315** [syj2010syj/w3x2txt#1]
正在执行:read_metadata
正在执行:read_metadata
正在执行:read_metadata
正在执行:read_metadata
正在执行:read_metadata
正在执行:read_metadata
正在执行:read_metadata
正在执行:read_metadata
正在执行:read_triggerdata
正在执行:read_triggerdata
文件无效:C:\Users\Administrator\Desktop\w3x2txt-master\meta\user\TriggerData.txt

正在执行:txt2obj
正在执行:txt2obj
正在执行:txt2obj
正在执行:txt2obj
正在执行:txt2obj
正在执行:txt2obj
正在执行:txt2obj
正在执行:txt2w3i
正在执行:fresh_wts
C:\Users\Administrator\Desktop\w3x2txt-master\build\lua.exe: ...nistrator\Deskto
p\w3x2txt-master\\src\impl\fresh_wts.lua:4: bad argument #1 to 'for iterator' (t
able expected, got nil)
stack traceback:
        [C]: in for iterator 'for iterator'
        ...nistrator\Desktop\w3x2txt-master\\src\impl\fresh_wts.lua:4: in functi
on 'w3x2txt.impl_fresh_wts'
        (...tail calls...)
        C:\Users\Administrator\Desktop\w3x2txt-master\src\make.lua:89: in local
'main'
        C:\Users\Administrator\Desktop\w3x2txt-master\src\make.lua:94: in main c
hunk
        [C]: in ?
请按任意键继续. . .
这个是错误吗？\meta\user\TriggerData.txt这个文件不存在，但是看到你的lua在尝试读取这个文件？

**Comment by syj2010syj** [comment]
这个文件是用于识别自定义UI,如果用了自定义UI或者更新版本的YDWE需要把TriggerData.txt复制到meta/user目录中供工具解析
不过看起来和这个问题无关

**Comment by syj2010syj** [comment]
我改了一下,你试下看看吧
近期可能会重构这个工具

**Comment by 1143910315** [comment]
恩，麻烦了，我能力不足，即使用了lua studio也难以读懂代码，不能帮你找原因，深感抱歉。
